// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["deps/under", "lib/utilities"], function(underscore, utilities) {
    var Action, B, Delta, Erase, H, Halt, Just, Left, LiveState, Maybe, Nothing, Right, State, Sym, Symbol, Tape, TuringMachine, Write, exported_names, _;
    _ = underscore._;
    Maybe = (function() {

      function Maybe(val) {
        if (val != null) {
          new Just(val);
        } else {
          new Nothing();
        }
      }

      return Maybe;

    })();
    Nothing = (function() {

      function Nothing() {}

      Nothing.prototype.isNothing = function() {
        return true;
      };

      Nothing.prototype.fmap = function(f) {
        return new Nothing();
      };

      return Nothing;

    })();
    Just = (function() {

      function Just(val) {
        this.val = val;
      }

      Just.prototype.isNothing = function() {
        return false;
      };

      Just.prototype.fromJust = function() {
        return this.val;
      };

      Just.prototype.fmap = function(f) {
        return new Just(f(this.val));
      };

      return Just;

    })();
    Maybe.Nothing = Nothing;
    Maybe.Just = Just;
    Symbol = (function() {

      function Symbol() {}

      Symbol.create = function(sym) {
        if ((!(sym != null)) || (sym === 'B')) {
          return new B();
        } else {
          return new Sym(sym);
        }
      };

      Symbol.prototype.inspect = function(depth) {
        return this.show();
      };

      return Symbol;

    })();
    Sym = (function(_super) {

      __extends(Sym, _super);

      function Sym(sym) {
        this.sym = sym;
      }

      Sym.prototype.blank = function() {
        return false;
      };

      Sym.prototype.show = function() {
        return this.sym;
      };

      Sym.prototype.canonical = function() {
        return this.sym;
      };

      Sym.prototype.matches = function(s) {
        return !s.blank() && this.sym === s.sym;
      };

      return Sym;

    })(Symbol);
    B = (function(_super) {

      __extends(B, _super);

      function B() {}

      B.prototype.blank = function() {
        return true;
      };

      B.prototype.show = function() {
        return 'B';
      };

      B.prototype.canonical = function() {
        return 'B';
      };

      B.prototype.matches = function(s) {
        return s.blank();
      };

      return B;

    })(Symbol);
    Symbol.Sym = Sym;
    Symbol.B = B;
    State = (function() {

      function State() {}

      State.create = function(state) {
        if ((!(state != null)) || (state === 'H') || (state === '')) {
          return new H();
        } else {
          return new LiveState(state);
        }
      };

      State.prototype.inspect = function(depth) {
        return this.show();
      };

      return State;

    })();
    LiveState = (function(_super) {

      __extends(LiveState, _super);

      function LiveState(state) {
        this.state = state;
      }

      LiveState.prototype.halt = function() {
        return false;
      };

      LiveState.prototype.show = function() {
        return this.state;
      };

      LiveState.prototype.canonical = function() {
        return this.state;
      };

      LiveState.prototype.matches = function(s) {
        return !s.halt() && this.state === s.state;
      };

      return LiveState;

    })(State);
    H = (function(_super) {

      __extends(H, _super);

      function H() {}

      H.prototype.halt = function() {
        return true;
      };

      H.prototype.show = function() {
        return 'H';
      };

      H.prototype.canonical = function() {
        return 'H';
      };

      H.prototype.matches = function(s) {
        return s.halt();
      };

      return H;

    })(State);
    State.LiveState = LiveState;
    State.H = H;
    Tape = (function() {

      function Tape(left, curr, right) {
        this.leftTape = left;
        this.curr = curr;
        this.rightTape = right;
        this.index = 0;
      }

      Tape.prototype.set_curr = function(sym) {
        return this.curr = sym;
      };

      Tape.prototype.move_left = function() {
        var _ref;
        this.rightTape.unshift(this.curr);
        this.curr = (_ref = this.leftTape.shift()) != null ? _ref : new B();
        return this.index = this.index - 1;
      };

      Tape.prototype.move_right = function() {
        var _ref;
        this.leftTape.unshift(this.curr);
        this.curr = (_ref = this.rightTape.shift()) != null ? _ref : new B();
        return this.index = this.index + 1;
      };

      Tape.prototype.show = function() {
        var l, ls, r, rs, sym;
        l = this.leftTape.slice(0).reverse();
        r = this.rightTape.slice(0);
        ls = (function() {
          var _i, _len, _results;
          _results = [];
          for (_i = 0, _len = l.length; _i < _len; _i++) {
            sym = l[_i];
            _results.push(sym.show());
          }
          return _results;
        })();
        rs = (function() {
          var _i, _len, _results;
          _results = [];
          for (_i = 0, _len = r.length; _i < _len; _i++) {
            sym = r[_i];
            _results.push(sym.show());
          }
          return _results;
        })();
        return (ls.concat(this.curr.show()).concat(rs)).join(' ');
      };

      return Tape;

    })();
    Action = (function() {

      function Action() {}

      Action.create = function(str) {
        switch (str) {
          case "E":
            return new Erase();
          case "L":
            return new Left();
          case "R":
            return new Right();
          case "H":
            return new Halt();
          default:
            if (str.charAt(0) === 'W') {
              return new Write(Symbol.create(str.slice(2, str.length - 1)));
            } else {
              throw "Unknown action";
            }
        }
      };

      Action.prototype.inspect = function(depth) {
        return this.show();
      };

      return Action;

    })();
    Erase = (function(_super) {

      __extends(Erase, _super);

      function Erase() {}

      Erase.prototype.type = function() {
        return "Erase";
      };

      Erase.prototype.show = function() {
        return 'E';
      };

      return Erase;

    })(Action);
    Write = (function(_super) {

      __extends(Write, _super);

      function Write(sym) {
        this.sym = sym;
      }

      Write.prototype.type = function() {
        return "Write";
      };

      Write.prototype.show = function() {
        return "W(".concat(this.sym.show()).concat(")");
      };

      return Write;

    })(Action);
    Left = (function(_super) {

      __extends(Left, _super);

      function Left() {}

      Left.prototype.type = function() {
        return "Left";
      };

      Left.prototype.show = function() {
        return "L";
      };

      return Left;

    })(Action);
    Right = (function(_super) {

      __extends(Right, _super);

      function Right() {}

      Right.prototype.type = function() {
        return "Right";
      };

      Right.prototype.show = function() {
        return "R";
      };

      return Right;

    })(Action);
    Halt = (function(_super) {

      __extends(Halt, _super);

      function Halt() {}

      Halt.prototype.type = function() {
        return "Halt";
      };

      Halt.prototype.show = function() {
        return "H";
      };

      return Halt;

    })(Action);
    Action.Erase = Erase;
    Action.Write = Write;
    Action.Left = Left;
    Action.Right = Right;
    Action.Halt = Halt;
    Delta = (function() {

      function Delta(action, nextState) {
        this.action = action;
        this.nextState = nextState;
      }

      return Delta;

    })();
    TuringMachine = (function() {

      function TuringMachine(program, state, tape) {
        this.program = program;
        this.state = state;
        this.tape = tape;
      }

      TuringMachine.prototype.currentDelta = function() {
        if (this.state.halt()) {
          return new Nothing();
        } else {
          return new Just(this.program[this.state.canonical()][this.tape.curr.canonical()]);
        }
      };

      TuringMachine.prototype.applyDelta = function(delta) {
        var action, nextState;
        action = delta.action, nextState = delta.nextState;
        this.state = nextState;
        switch (action.type()) {
          case "Erase":
            return this.tape.set_curr(new B());
          case "Write":
            return this.tape.set_curr(action.sym);
          case "Left":
            return this.tape.move_left();
          case "Right":
            return this.tape.move_right();
          case "Halt":
            return this.tape;
        }
      };

      TuringMachine.prototype.initialize = function(state, initialTape) {
        var curr, left, right, _ref;
        this.state = state;
        left = [];
        curr = (_ref = initialTape.shift()) != null ? _ref : new B();
        right = initialTape != null ? initialTape : [];
        return this.tape = new Tape(left, curr, right);
      };

      TuringMachine.prototype.halted = function() {
        return this.state.halt();
      };

      TuringMachine.prototype.step = function() {
        var delta;
        delta = this.currentDelta();
        if (!delta.isNothing()) {
          return this.applyDelta(delta.fromJust());
        } else {
          throw "Can't step from halted state";
        }
      };

      TuringMachine.prototype.showApplicableRule = function() {
        var show_rule;
        show_rule = function(action, nextState) {};
        return state.show() + ": " + curr.show() + " -> " + action.show() + "; " + nextState.show();
      };

      TuringMachine.prototype.showCurrentTape = function() {
        return this.tape.show();
      };

      return TuringMachine;

    })();
    exported_names = {
      TM: TuringMachine,
      TuringMachine: TuringMachine,
      Action: Action,
      Delta: Delta,
      State: State,
      Symbol: Symbol,
      Tape: Tape,
      Maybe: Maybe
    };
    return exported_names;
  });

}).call(this);
